### ISSUE TITLE
Sidemenu toevoegen

### ISSUE THREAD

**Issue by christiaangoossens** [Verictas/SGN-App#2]
We hebben een menu nodig met het http://ionicframework.com/docs/components/#menus component nodig. Daarin staat een foto, de informatie over de leerling/docent en de links naar de betreffende pagina's. Je kunt ook klikken op de leerling voor de leerlingkaart, of op een optiepaneel om uit te loggen.

**Comment by lauw70** [comment]
Het lijkt me handig dat we beginnen met deze issue. Dan kunnen we hierop verder werken.
Als dit af is gaat de rest denk ik makkelijker

**Comment by lauw70** [comment]
voorstel voor volgorde van pagina's in menu:

0. boven aan de lijst een icon met foto -> verwijst naar gebruikers pagina
1. rooster
2. huiswerk
3. cijfers
4. absenties
5. meldingen

**Comment by christiaangoossens** [comment]
Voltooid met commit 0ebc673, de menupagina's worden toegevoegd wanneer de toepasselijke versie van de app wordt vrijgegeven.
